export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const UPDATE_MESSAGES_STATUS = 'UPDATE_MESSAGES_STATUS';

export const UPDATE_APPLICATION_SETTINGS = 'UPDATE_APPLICATION_SETTINGS';
export const RESET_APPLICATION_SETTINGS = 'RESET_APPLICATION_SETTINGS';